爱因斯坦求和约定（Einsum）:</br>
一种通过下标标记维度实现张量运算的数学符号系统，其核心规则是重复下标自动求和，唯一下标保留维度。

In [12]:
import torch

In [14]:
q = torch.tensor([[1, 2, 3],
                  [4, 5, 6]])

k = torch.tensor([[0, 1, 2],
                  [3, 4, 5]])

output = torch.einsum("nc,nc->n", [q, k])
print(output)  # Output: tensor([ 8, 62]) # 样本 0：1*0 + 2*1 + 3*2 = 0 + 2 + 6 = 8; 样本 1：4*3 + 5*4 + 6*5 = 12 + 20 + 30 = 62
final_output = output.unsqueeze(-1)
print(final_output)  # Output: tensor([[ 8], [62]]) # 增加了一个维度

tensor([ 8, 62])
tensor([[ 8],
        [62]])


In [18]:
import torch

q = torch.tensor([[1],[2],[3]])
k = torch.tensor([[0],[1],[2]])

# 使用 einsum 计算点积
logits = torch.einsum("nc,nc->n", [q, k])
print("原始输出:", logits, logits.shape)

# 增加维度
logits = logits.unsqueeze(-1)
print("最终结果:", logits, logits.shape)


原始输出: tensor([0, 2, 6]) torch.Size([3])
最终结果: tensor([[0],
        [2],
        [6]]) torch.Size([3, 1])


In [ ]:
q = torch.tensor([[1, 2, 3],
                  [4, 5, 6]])  # shape (2,3)

queue = torch.tensor([[0, 1, 2, 3],
                     [4, 5, 6, 7],
                     [7, 8, 9, 10]])  # shape (3,4)

# 矩阵乘法 nc,ck->nk
l_neg = torch.einsum("nc,ck->nk", [q, queue.clone().detach()]) 
'''
    queue.clone().detach()的作用可以总结为：
        复制数据：通过 .clone() 创建一个与原始 queue 数据完全相同的新张量。
        隔离影响：通过 .detach() 确保新张量不参与梯度计算，且任何操作都不会影响原始 queue 的值。
'''
print(l_neg)

tensor([[ 29,  35,  41,  47],
        [ 62,  77,  92, 107]])


In [ ]:
# 两个向量的点积
a = torch.tensor([1, 2, 3])  # shape (3,)
b = torch.tensor([4, 5, 6])  # shape (3,)
torch.einsum('i,i->', a, b)  # tensor(32)

tensor(32)

In [ ]:
# 矩阵乘法
A = torch.tensor([[1, 2], [3, 4]]) # shape (2, 2), 下标标记为 n,c
B = torch.tensor([[5, 6], [7, 8]]) # shape (2, 2), 下标标记为 c,k
result = torch.einsum('nc,ck->nk', A, B)
print(result)  # 输出: tensor([[19, 22], [43, 50]])  e.g.：选择 A 的第 i=0 行：[1, 2], 选择 B 的第 k=0 列：1×5 + 2×7 = 5 + 14 = 19

tensor([[19, 22],
        [43, 50]])


In [ ]:
# 张量缩并
C = torch.tensor([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
result = torch.einsum('ijk->jk', C)
print(result)  # 输出: tensor([[6, 8], [10, 12]]) 1+5 2+6 3+7 4+8

tensor([[ 6,  8],
        [10, 12]])


In [ ]:
# 张量迹
D = torch.tensor([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
result = torch.einsum('ii->', D) # ii 就是取对角线：1+5+9=15
print(result)  # 输出: tensor(15)

tensor(15)


In [10]:
a = torch.randn(2,3,5,7,9)
# i = 7, j = 9
b = torch.einsum('...ij->...ji', [a])
print(b.shape)  # 输出: torch.Size([2, 3, 5, 9, 7])

torch.Size([2, 3, 5, 9, 7])


更多高级用法：https://blog.csdn.net/bj_zhb/article/details/136869289